// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProfile(arg1, arg2) {
  return window['go']['main']['App']['ApplyProfile'](arg1, arg2);
}

export function CancelOAuthLogin() {
  return window['go']['main']['App']['CancelOAuthLogin']();
}

export function ChooseAppDataFolder() {
  return window['go']['main']['App']['ChooseAppDataFolder']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateProfileWithOAuth() {
  return window['go']['main']['App']['CreateProfileWithOAuth']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportAuthJson(arg1, arg2) {
  return window['go']['main']['App']['ExportAuthJson'](arg1, arg2);
}

export function ImportAuthProfile() {
  return window['go']['main']['App']['ImportAuthProfile']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenProfilesFolder() {
  return window['go']['main']['App']['OpenProfilesFolder']();
}

export function OpenUserDataFolder() {
  return window['go']['main']['App']['OpenUserDataFolder']();
}

export function RefreshUsageState(arg1) {
  return window['go']['main']['App']['RefreshUsageState'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ReorderProfiles(arg1) {
  return window['go']['main']['App']['ReorderProfiles'](arg1);
}

export function RestartCodex() {
  return window['go']['main']['App']['RestartCodex']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
