// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyProfile(arg1:string,arg2:boolean):Promise<main.AppState>;

export function CancelOAuthLogin():Promise<Record<string, boolean>>;

export function ChooseAppDataFolder():Promise<string>;

export function CreateProfile(arg1:string):Promise<main.AppState>;

export function CreateProfileWithOAuth():Promise<main.AppState>;

export function DeleteProfile(arg1:string):Promise<main.AppState>;

export function ExportAuthJson(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ImportAuthProfile():Promise<main.AppState>;

export function LoadState():Promise<main.AppState>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenProfilesFolder():Promise<void>;

export function OpenUserDataFolder():Promise<void>;

export function RefreshUsageState(arg1:boolean):Promise<main.AppState>;

export function RenameProfile(arg1:string,arg2:string):Promise<main.AppState>;

export function ReorderProfiles(arg1:Array<string>):Promise<main.AppState>;

export function RestartCodex():Promise<main.AppState>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppState>;
